version: '2.3'

services:
  python:
    environment:
      GUNICORN_CMD_ARGS: '--bind=0.0.0.0:5000'
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ..:/app/
    environment: